[NVIDIA] Log FW Update error
DavidZagury/sonic-buildimage pull request #26
Opened 2023-01-16 11:08 UTC by DavidZagury

#### Why I did it
To have information about the cause of FW update failure in the log.

#### How I did it
In case the FW update has failed the update tool will give the cause of the failure in the output in the last line, starting with "Fail".
When running the tool, in case of a failed update, we will parse the output to retrieve the cause and log it.
```
Device #1:
 ----------
 
 Device Type:      ConnectX6DX
   Part Number:      MCX623106AN-CDA_Ax
   Description:      ConnectX-6 Dx EN adapter card; 100GbE; Dual-port QSFP56; PCIe 4.0/3.0 x16;
   PSID:             MT_0000000359
   PCI Device Name:  /dev/mst/mt4125_pciconf0
   Base GUID:        0c42a103007d22d4
   Base MAC:         0c42a17d22d4
   Versions:         Current        Available     
      FW             22.32.0498     22.32.0498    
      PXE            3.6.0500       3.6.0500      
      UEFI           14.25.0015     14.25.0015    
 
 Status:           Forced update required
 
---------
 Found 1 device(s) requiring firmware update...
 
Device #1: Updating FW ...     
 FSMST_INITIALIZE -   OK          
 Writing Boot image component -   OK          
 Fail : The Digest in the signature is wrong
```

#### How to verify it
Create a scenario where FW update fails (i.e. corrupted FW) and use the mlnx-fw-update script to try to update the FW.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Description for the changelog

#### Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-01-17 11:21 UTC, keboliu approved these changes

2023-01-17 11:22 UTC, keboliu commented on platform/mellanox/mlnx-fw-upgrade.j2
> +        ExitFailure "FW Update command failed: ${COMMAND} with error:" ${failure_msg}
ExitFailure "FW Update command : ${COMMAND} failed with error:" ${failure_msg}

2023-01-18 08:56 UTC, nazariig requested changes

2023-01-18 08:56 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +        ExitFailure "FW Update command: ${COMMAND} failed with error:" ${failure_msg}
@DavidZagury it won't print to the syslog. Suggest to rework.

2023-01-18 13:05 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +            output=$(eval "${COMMAND}")
@DavidZagury please use tab with 4 spaces

2023-01-18 13:05 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +            output=$(eval "${COMMAND}") >/dev/null 2>&1
@DavidZagury please use tab with 4 spaces

2023-01-18 13:07 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +        failure_msg=${output#*Fail : }
@DavidZagury please wrap command with double quotes

2023-01-18 13:08 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +        ExitFailure "FW Update command: ${COMMAND} failed with error:" ${failure_msg}
@DavidZagury please include `${failure_msg}` into the common double quotes

2023-01-19 11:54 UTC, nazariig requested changes

2023-01-19 11:54 UTC, nazariig commented on platform/mellanox/mlnx-fw-upgrade.j2
> +        ExitFailure "FW Update command: ${COMMAND} failed with error:" ${failure_msg}
```suggestion
        ExitFailure "FW Update command: ${COMMAND} failed with error: ${failure_msg}"
```

2023-01-24 19:52 UTC, closed without merging