[Mellanox] [SKU] Mellanox-SN4700-O8V48 SKU added
DavidZagury/sonic-buildimage pull request #46
Opened 2023-11-30 17:33 UTC by DavidZagury

#### Why I did it

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ] 

#### Description for the changelog

#### Link to config_db schema for YANG module changes

#### A picture of a cute animal (not mandatory but encouraged)

2023-11-30 17:58 UTC, dgsudharsan requested changes

2023-11-30 17:58 UTC, dgsudharsan commented on device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8V48/sai.profile
> +SAI_DUMP_MFT_CFG_PATH=/etc/sonic/mft/fwtrace_cfg
We need to add store and forward for MSFT SKUs https://github.com/sonic-net/sonic-buildimage/blob/04bb0d34947037c182bf8e3b9818dd693f232822/device/mellanox/x86_64-mlnx_msn4700-r0/Mellanox-SN4700-O8C48/sai.profile#L5

2023-12-02 00:16 UTC, dgsudharsan approved these changes

2023-12-04 09:43 UTC, stephenxs approved these changes

2023-12-05 02:43 UTC, dgsudharsan approved these changes

2023-12-08 19:43 UTC, closed without merging